# Generated by Django 4.2.17 on 2025-01-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
